--- 
abstract: RT extension installer
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Module-Install-RTx
no_index: 
  directory: 
    - inc
    - t
requires: 
  Module::Install::Admin: 0.29
version: 0.20
