name: Module-Install-RTx
version: 0.06
abstract: RT extension installer
license: perl
distribution_type: module
requires:
  Module::Install::Admin: 0.29
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.33
