--- 
abstract: RT extension installer
author: 
  - Audrey Tang <cpan@audreyt.org>
distribution_type: module
generated_by: Module::Install version 0.68
license: mit
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Module-Install-RTx
no_index: 
  directory: 
    - inc
    - t
provides: 
  Module::Install::RTx: 
    file: lib/Module/Install/RTx.pm
    version: 0.22
  Module::Install::RTx::Factory: 
    file: lib/Module/Install/RTx/Factory.pm
requires: 
  Module::Install::Admin: 0.4
  perl: 5.8.0
version: 0.22
